seleniumhub:
 image: selenium/hub
 ports:
 - "5555:4444"
 environment:
   GRID_TIMEOUT: 1800000
   GRID_BROWSER_TIMEOUT: 1800000
   GRID_CLEAN_UP_CYCLE: 60000
chromenode:
 image: thirdshelf/node-chrome-debug:3.7.1
 volumes:
     - /dev/shm:/dev/shm
 ports:
 - "5900"
 links:
 - seleniumhub:hub
 environment:
    NODE_MAX_SESSION: 10
    NODE_MAX_INSTANCES: 10
